:Title: OGC Geospatial Data Requirements SWG Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: 2024-03-23
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    OGC 24-011
|Category: OGC(R) Standards Working Group Charter
|Authors:   Joan Maso and Alba Brobia
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2024 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the OGC Geospatial Data Requirements (GDR) SWG Charter. The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

Data requirements are the specifications describing what data a project needs to collect, store, analyze, and present to achieve the objectives of such a project. Data requirements are derived from the scope and objectives of a project and condition the feasibility of the results. However, during the study on previous existing models for describing geospatial data requirementsfootnote:[https://doi.org/10.3390/rs15061589], the autors of this charter were not able to detect any specific standards neither in the Open Geospatial Consortium nor in any other standardization body. The identification of this gap represents an opportunity for the **Geospatial Data Requirements** standardization.

The purpose of this SWG is:

* to develop open Standards that enable the robust, transparent, and consistent use of geospatial data requirements and they FAIRness

* to set a common background that satisfies current developments on geospatial data requirement systems and enable interoperable new ones.

== Business value proposition

Understanding data user requirements is a crucial initial step for producing data that fits its intended purpose. However, often data providers create geospatial dataset that they believe are feasible and useful but they might do not completely know the real needs of users, resulting in reduced effective utilization of this data. Requirements can be collected and used to define and provide a single data product, or can be used to define a collection of datasets that cover a particular domain.

The Business value proposition of this SWG is:

* to contribute to the creation of a marketplace where user needs are connected to data producers. This way when requirement can not be covered with existing datasets, data producers can fill the gaps in the current data products and satisfy the user needs.

* to specify a set of products that needs to be created maintain and curated to fulfill the needs of a community working in a particular domain.

The following list is considered are target users for this initiative: Group on Earth Observations (GEO), EuroGEO, data initiatives, Earth Observation networks, Research infrastructures, data provider (including cartographic institutes, public organizations and private companies), research and innovation projects requiring geospatial data.

== Scope of work

The Scope of Work of the GDR SWG encompasses the following activities:

* Identification of core needs for GDRs

* Standardization of a data model to describe user requirements. While no preexisting standard was detected, some implementations of data requirements systems exist and will be used as a baseline to define a new OGC standard

* Standardization of a OGC API to create, modify, retrieve and delete requirements. While no preexisting standard was detected, some implementations exist. The group will study the possibility to associate a requirement to the concept of "feature" and use OGC API features as a baseline for the new OGC API

* Promotion of the use of standardized requirements by users (e.g. projects using geospatial data) and producers.


=== Statement of relationship of planned work to the current OGC Standards baseline

A data model for geospatial user requirements can be done using metadata that describes the dataset. While metadata is not commonly defined by OGC, there are precedents of OGC standard reusing metadata and extending metadata such as Catalogue Service for the Web (CSW) and Geospatial User Feedback (GUF).

The planned work for GDR will rely upon the existing OGC and ISO standards, such as the following:

* ISO 19115 (OGC abstract Topic 11 - Metadata)

* OGC abstract Topic Topic 20 - Observations, measurements and samples

* OGC API Features 

* OGC API Records

* OGC Geospatial User Feedback

=== What is out of scope?
The following activities are out of scope for this GDR SWG:

* Define a list of domain specific geospatial data products
* Define metadata to describe existing datasets.

=== Specific existing work used as starting point
The reference work relevant for this GDR SWG is the following:

* Copernicus In Situ Component Information System (CIS2)footnote:[https://cis2.eea.europa.eu/about]

* National Oceanic and Atmospheric Administration - Office of System Architecture and Advanced Planning (NOAA - OSAAP)footnote:[https://www.nesdis.noaa.gov/node/11226]

* World Meteorological Organization - Observing Systems Capability Analysis and Review Tool (WMO OSCAR/Requirements)footnote:[https://space.oscar.wmo.int/observingrequirements]

* Geospatial in-situ requirements (G-reqs)footnote:[https://doi.org/10.3390/rs15061589]

The intention of the group is to analyze the previous work as starting point for the new Standards.

=== Is this a persistent SWG

[ ] YES

[x] NO

=== When can the SWG be inactivated

When the two planned standards (data model and OGC API) has been approved and there are not pending issues the group will be inactivated

== Description of deliverables

=== Initial deliverables
The following deliverables will be included in the initial results of the GDR SWG:

* provision of common standard data model for Geospatial Data Requirements

* make the Geospatial Data Requirements FAIR by means of the new OGC APIs.

This two deliverables will be done in sequence starting by defining the data model for geospatial data requirements.  The initial objective of the group is to be able to write the first complete standard draft in 9 month and present it to the OAB for consideration. Once the data model for data requirements is drafted and submitted to the OAB, the second deliverable will be started. 

=== Additional SWG tasks

No additional tasks are foreseen at this point.

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated audience / participants

Any actor that is involved in using data in their activities that have previous experiences in defining potential datasets are invited to participate in this group.

In particular, activities related with preparing data and processing data are welcome to contribute to this work. Examples are Analysis Ready Data (ARD) and OGC API Processes. Thematic groups that know the needs of their communities can also be useful contributors such as MetOcean.  

== Domain Working Group endorsement

The Metadata and Cataloguing DWG (MetaCat.DWG) seems the right DWG to endorse this group

== Other informative information about the work of this SWG

=== Collaboration

The SWG would like to use GitHub  as the collaboration environment for management of Standard document and related content.

This draft was initially started in https://github.com/joanma747/CharterDataRequirements and will be move to the "opengeospatial" GitHub as the work progresses.

=== Similar or applicable standards work (OGC and elsewhere)

No international standards about the topic were detected.

=== Details of first meeting

Next Members Meeting or telephone conference call before.

=== Projected on-going meeting schedule
The GRI SWG will progress its work through:

* Regular monthly online meetings; and

* Organization of SWG sessions at the OGC Member Meetings.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|Name |Organization
|TBD | NOAA
|TBD | EEA
|José Miguel Rubio | Copernicus In Situ component
|TBD | GEO
|Joan Maso and Alba brobia | CREAF
|===

=== Conveners
Joan Maso and Alba Brobia are starting the SWG process but others are welcome.


== References

See footnotes includes this document. 
